### ISSUE TITLE
node.js connect server (e.g. express) with OAS3 - design first approach

### ISSUE THREAD

**Issue by kiebzak** [APIs-guru/awesome-openapi3#21]
Please take a look and tell what do you think at https://www.npmjs.com/package/@smartrecruiters/openapi-first - an extensible module helping linking business logic code with OAS3 in node.js, providing also middlewares for parsing, setting defaults, validation of operation attributes like requestBody, parameters, content-type. I believe this approach really encourage developers to design first, then code in API development.

**Comment by stevehu** [comment]
@kiebzak Good post and design first is the only approach for enterprise scale. I have written an article the other day that compares design first vs code first and it might help developers to make decisions. 

https://www.networknt.com/design/design-first/

**Comment by kiebzak** [comment]
Should I explain sth in more detail? :)

**Comment by MikeRalphson** [comment]
> Should I explain sth in more detail?

No, sorry, this issue slipped through the net. I should have perhaps asked you to create a PR - as we only list projects, not review them, but I've added it now. It may take a few moments for github pages to refresh.

Cheers!
