### ISSUE TITLE
Add falcon-heavy

### ISSUE THREAD

**Issue by NotJustAToy** [APIs-guru/awesome-openapi3#45]
https://github.com/NotJustAToy/falcon-heavy we introduce new python package for server-side support of OAS3. It can be used with Django, Falcon and Flask.

**Comment by MikeRalphson** [comment]
If you tag your project with the github topic `openapi3` then it should be automatically picked up by the next update.

**Comment by NotJustAToy** [comment]
Thank you! It already has this topic.
