### ISSUE TITLE
Suggested TypeScript package: openapi-typescript

### ISSUE THREAD

**Issue by drwpow** [APIs-guru/awesome-openapi3#66]
Hello! I’m the maintainer of https://www.npmjs.com/package/openapi-typescript, which is useful for generating robust TypeScript schemas from an OpenAPI schema. Would this package be a good fit for this site? Thanks!

**Comment by MikeRalphson** [comment]
Hi, sorry for the long delay. If you add the topic `openapi3` and/or `openapi3_1` to your GitHub repo then your project will automatically get picked up and added to this repo and the new official OAS tooling repo (https://oai.github.io/Tooling/)

**Comment by drwpow** [comment]
No worries at all. Thank you!
