### ISSUE TITLE
A project with the proper topic is not added

### ISSUE THREAD

**Issue by Fatal1ty** [APIs-guru/awesome-openapi3#72]
I added openapi3 topic to my project https://github.com/Fatal1ty/openapify a few days ago but it still hasn’t appeared on the site. Am I missing something?

**Comment by MikeRalphson** [comment]
Thanks, I'll take a look. Do you know if your tool has shown up on https://tools.openapis.org ?

**Comment by Fatal1ty** [comment]
> Do you know if your tool has shown up on https://tools.openapis.org ?

No, It hasn’t.

**Comment by MikeRalphson** [comment]
OK, will take a close look, thanks.

**Comment by MikeRalphson** [comment]
We currently only fetch the first (I think it's 200) repos from the GraphQL endpoint, ordered by stars. Your project may not be making that list. I'll see if I can add pagination to the query.

**Comment by Fatal1ty** [comment]
> We currently only fetch the first (I think it's 200) repos from the GraphQL endpoint, ordered by stars. Your project may not be making that list. I'll see if I can add pagination to the query.

Thank you for a quick investigation! I don't know if it's related but I can see projects with only one star in response of the Tools API (https://apis.guru/awesome-openapi3/api/tools.json). In any case, if adding pagination isn't difficult and you're for it, then I'd be appreciated. Otherwise, it would be helpful for future coming projects to see a note somewhere about the limit of projects.

**Comment by MikeRalphson** [comment]
I've moved off the GraphQL endpoint with it's low limitations, and I can see your project will now be added. Will close when confirmed.

**Comment by MikeRalphson** [comment]
The projects with only one star were probably added when all the projects fit in the GraphQL query! Anyway, your project is now listed and I've put it in the code-gen category, hope that's right.

**Comment by Fatal1ty** [comment]
Thank you! I think code-gen category is ok.
